{
 "title": "My_Application_NodeJS",
 "time": { "from": "2025-02-28T13:01:08.161Z", "to": "2025-02-28T14:18:26.967Z" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Active Handles",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nodejs_active_handles_total", "legendFormat": "{{NodeJS_APP}}" }
   ]
  },
  {
   "title": "Event Loop Lag (Avg in Seconds)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_mean_seconds",
     "legendFormat": "{{NodeJS_APP}}"
    }
   ]
  },
  {
   "title": " Garbage Collection Duration (Total Seconds)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nodejs_gc_duration_seconds_sum)",
     "legendFormat": "{{NodeJS_APP}}"
    }
   ]
  },
  {
   "title": " Heap Used (MB)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nodejs_heap_space_size_used_bytes) / 1024 / 1024",
     "legendFormat": "{{NodeJS_APP}}"
    }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m]) * 100",
     "legendFormat": "{{NodeJS_APP}}"
    }
   ]
  },
  {
   "title": "Memory Usage (Resident Set in MB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 10, "y": 4 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes / 1024 / 1024",
     "legendFormat": "{{NodeJS_APP}}"
    }
   ]
  }
 ]
}